version = 3
final_space = true

# First line
[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '╭'
    type = 'text'
    foreground = '#888888'

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  filler = '<#888888>─</>'

  [[blocks.segments]]
    template = '─'
    type = 'text'
    foreground = '#888888'

# Second line
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    template = '│'
    foreground = '#aaaaaa'

  [[blocks.segments]]
    type = 'text'
    template = '['
    foreground = '#cc6ce7'

  [[blocks.segments]] # OS
    type = 'os'
    template = '{{ .Icon }}'
    foreground = '#f00ec6'

  [[blocks.segments]] # Username
    type = 'text'
    template = ' {{ .UserName }}]'
    foreground = '#cc6ce7'

  [[blocks.segments]] # Git
    type = 'git'
    template = '[{{ .UpstreamIcon }}{{ .RepoName }} {{ .HEAD }} {{ .BranchStatus }}]'
    foreground = 'blue'

    [blocks.segments.properties]
      fetch_status = true
      fetch_upstream_icon = true
      cache_duration = 'none'

  [[blocks.segments]] # Python
    type = 'python'
    template = '{{ if ne .Venv "base" }}[ {{ .Venv }}]{{ end }}'
    foreground = 'green'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]] # Rust
    type = 'rust'
    template = '[󱘗 {{ .Full }}]'
    foreground = '#f59040'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]] # Battery
    type = 'battery'
    template = '[{{ .Icon }}{{ .Percentage }}%]'
    foreground_templates = [
      '{{ if lt .Percentage 20 }}#ff0000{{ end }}',
      '{{ if lt .Percentage 40 }}#ffa700{{ end }}',
      '{{ if lt .Percentage 60 }}#fff400{{ end }}',
      '{{ if lt .Percentage 80 }}#a3ff00{{ end }}',
      '{{ if lt .Percentage 100 }}#2cba00{{ end }}'
    ]

    [blocks.segments.properties]
      cache_duration = 'none'
      discharging_icon = '󰂍 '
      charging_icon = '󰂐 '
      charged_icon = '󰁹 '

  [[blocks.segments]] # Time
    type = 'time'
    template = '[ {{ .CurrentDate | date .Format }}]'
    foreground = '#00ffff'

    [blocks.segments.properties]
      cache_duration = 'none'
      time_format = '3:04'

  [[blocks.segments]] # oh-my-posh update
    type = 'upgrade'
    template = '[!]'
    foreground = '#ff0000'

# Third line
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    template = '│'
    foreground = '#cccccc'

  [[blocks.segments]] # Project
    type = 'project'
    template = '[ {{ .Name }}]'
    foreground = '#ff00ae'

  [[blocks.segments]] # Path
    type = 'path'
    template = '[{{ .Path }}]'
    foreground = '#ffde59'

    [blocks.segments.properties]
      cache_duration = 'none'
      home_icon = ' ~'
      style = 'agnoster_short'
      max_depth = 3

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]] # Execution time
    type = 'executiontime'
    template = '[{{ .FormattedMs }}]'
    foreground = '#ffffff'

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]] # Return code
    type = 'status'
    template = '[{{ .String }}]'
    foreground_templates = ['{{ if eq .Code 0 }}green{{ else }}red{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'

# Fourth line
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    template = '╰─'
