version = 3
final_space = true

# First line
[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '╭'
    type = 'text'

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  filler = '─'

  [[blocks.segments]]
    template = ' <'
    type = 'text'

# Second line
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    template = '│'

  [[blocks.segments]] # Username
    type = 'text'
    template = '[ {{ .UserName }}]'
    foreground = '#cc6ce7'

  [[blocks.segments]] # Git
    type = 'git'
    template = '[{{ .UpstreamIcon }}{{ .RepoName }} {{ .HEAD }} {{ .BranchStatus }}]'
    foreground = 'blue'

    [blocks.segments.properties]
      fetch_status = true
      fetch_upstream_icon = true
      cache_duration = 'none'

  [[blocks.segments]] # Python
    type = 'python'
    template = '{{ if ne .Venv "base" }}[ {{ .Venv }}]{{ end }}'
    foreground = 'green'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]] # Battery
    type = 'battery'
    template = '[{{ .Icon }}{{ .Percentage }}%]'
    foreground_templates = [
      '{{ if lt .Percentage 20 }}#ff0000{{ end }}',
      '{{ if lt .Percentage 40 }}#ffa000{{ end }}',
      '{{ if lt .Percentage 60 }}#fff700{{ end }}',
      '{{ if lt .Percentage 80 }}#c0ff00{{ end }}',
      '{{ if lt .Percentage 100 }}#00ff00{{ end }}'
    ]

    [blocks.segments.properties]
      cache_duration = 'none'
      discharging_icon = '󰂍 '
      charging_icon = '󰂐 '
      charged_icon = '󰁹 '

  [[blocks.segments]] # Time
    type = 'time'
    template = '[ {{ .CurrentDate | date .Format }}]'
    foreground = '#00ffff'

    [blocks.segments.properties]
      cache_duration = 'none'
      time_format = '3:04'

  [[blocks.segments]] # oh-my-posh update
    type = 'upgrade'
    template = '[!]'
    foreground = '#ff0000'

# Third line
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    template = '│'

  [[blocks.segments]] # Path
    type = 'path'
    template = '[{{ .Path }}]'
    foreground = '#ffde59'

    [blocks.segments.properties]
      cache_duration = 'none'
      home_icon = ' ~'
      style = 'mixed'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]] # Execution time
    type = 'executiontime'
    template = '[{{ .FormattedMs }}]'
    foreground = '#ffffff'

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]] # Return code
    type = 'status'
    template = '[{{ .String }}]'
    foreground_templates = ['{{ if eq .Code 0 }}green{{ else }}red{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'

# Fourth line
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    template = '╰ >'
